export const data = [
    ["The LORD is my Shepherd.jpeg", "Oil on Canvas. 60x48 in. 2025.", "Psalm 23"],
    ["Lead me to the Still Waters, O LORD.jpeg", "Oil on Canvas. 30x48 in. 2025.", "Psalm 23"],
    ["Lead me in paths of Righteousness, for Your name's sake, O LORD.jpeg", "Oil on Canvas. 30x40 in. 2025.", "Psalm 23"],
    ["There is a river whose streams shall make glad the city of God, The holy place of the tabernacle of the Most High.jpeg", "Oil on Canvas. 30x48 in. 2025.", "Psalm 46"],
    ["Lead me to the Rock that is Higher than I.jpeg", "Oil on Canvas. 36x60 in. 2025.", "Psalm 61"],
    ["Be Still and Know I am God.jpeg", "Oil on Canvas. 24x30 in. 2025.", "Psalm 46"],
    ["The entrance of your word gives light.jpeg", "Oil paint on Canvas. 30x40 in. 2026.", "Psalm 119"],
    ["My help comes from the Lord, which made heaven and earth.jpeg", "Oil paint on Canvas. 30x40 in. 2026.", "Psalm 121"],
    ["Hind's feet on high places.jpeg", "Oil paint on Canvas. 30x40 in. 2026.", "Psalm 18"],
    ["He utters a word and the earth melts.jpeg", "Oil on Canvas Panel. 8x10 in. 2025.", "Psalm 46"],
    ["I will both lie down in peace, and sleep. For You alone, O Lord, make me dwell in safety..jpeg", "Oil on Gesso Wood Panel. 5x7 in. 2025.", "Psalm 4"],
    ["Hart Lake, MI.jpeg", "Oil on Gesso Wood Panel. 5x7 in. 2025."],
    ["The Wheat Harvest.jpeg", "Oil on Canvas. 48x72 in. 2025."],
    ["Revelation Throne Room in Flowers.jpeg", "Oil on Canvas. 24x30 in. 2025.", "Revelation 4"],
    ["The Martyr.jpeg", "Prismacolor and pencil on paper. 5x7 in. 2025."],
    ["Moses at the Red Sea.jpeg", "Oil on Canvas. 48x54 in. 2025.", "Exodus 14"],
    ["The Burning Bush.jpeg", "Oil on Canvas. 36x48 in. 2025.", "Exodus 3"],
    ["The Lamb Who Was Slain.jpeg", "Oil on Canvas. 16x20 in. 2025.", "Revelation 5"],
    ["Jesus.jpg", "Oil paint on Canvas. 20x20 in. 2024."],
    ["David.jpeg", "Oil Paint on Canvas. 24x30 in. 2024."],
];